name: Build container image

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 2 * * 0'

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v4
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          trucksnl/google-cloud-sdk
          ghcr.io/trucksnl/google-cloud-sdk
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        file: ./Dockerfile
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: |
          linux/amd64
          linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: |
          trucksnl/google-cloud-sdk:alpine
          trucksnl/google-cloud-sdk:alpine-v${{ github.run_number }}
          ghcr.io/trucksnl/google-cloud-sdk:alpine
          ghcr.io/trucksnl/google-cloud-sdk:alpine-v${{ github.run_number }}
